apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: outline
spec:
  version: "3.0.0-alpha-31+k8s-1.34"
  extensions:
    helmCharts:
      - chart:
          name: cert-manager
          chartVersion: "v1.16.3"
        releaseName: cert-manager
        namespace: cert-manager
        weight: -1
        values:
          crds:
            enabled: true
          image:
            repository: 'repl{{ ReplicatedImageName (HelmValue ".image.repository") true }}'
          webhook:
            image:
              repository: 'repl{{ ReplicatedImageName (HelmValue ".webhook.image.repository") true }}'
          cainjector:
            image:
              repository: 'repl{{ ReplicatedImageName (HelmValue ".cainjector.image.repository") true }}'
          acmesolver:
            image:
              repository: 'repl{{ ReplicatedImageName (HelmValue ".acmesolver.image.repository") true }}'
          startupapicheck:
            image:
              repository: 'repl{{ ReplicatedImageName (HelmValue ".startupapicheck.image.repository") true }}'
      - chart:
          name: traefik
          chartVersion: "39.0.7"
        releaseName: traefik
        namespace: traefik
        values:
          service:
            type: NodePort
          ports:
            web:
              nodePort: 80
            websecure:
              nodePort: 443
          image:
            registry: 'repl{{ ReplicatedImageRegistry (HelmValue ".image.registry") }}'
            repository: 'repl{{ ReplicatedImageRepository (HelmValue ".image.repository") true }}'
